### ISSUE TITLE
Fix documentation to show that validators are disabled by default

### ISSUE THREAD

**Issue by CloudoguSiebels** [cloudogu/gitops-build-lib#35]
In https://github.com/cloudogu/gitops-build-lib/commit/ef676df34eb798971073d6b6378a70a97d9e9a99 the validators kubeval and helmkubeval were disabled. 

The README suggests that all these validators are enabled by default: https://github.com/cloudogu/gitops-build-lib/tree/main#validators

**Comment by schnatterer** [comment]
Fixed by #43
